# These are supported funding model platforms

github: pods-framework, sc0ttkclark # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: # Replace with a single Open Collective username
custom: https://friends.pods.io # Replace with a single custom sponsorship URL
